language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: test
      script: "npm run test:clean && npm run test"
    - stage: build
      script: "npm run build"